<#assign orderForm = 

{
"cartRPrice":100,
"cartOriRPrice":100,
"expOriPrice":100,
"expUserPrice":10,
"expSysPayPrice":10,
"orderFormPayMethod":1,

"actionList":[
    {"actId":123,
    "title":"美容辅组工具品牌促销专场",
    "effectDesc":"订单已满200减20",
    "tagList":[
    {"title":"活动名称","desc":"满200减30"},
    {"title":"活动名称","desc":"满200减50"}
    ],
    "cartList":[
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	}
    	]
	},
	{"actId":123,
    "title":"美容辅组工具品牌促销专场",
    "effectDesc":"订单已满200减20",
    "tagList":[
    {"title":"活动名称","desc":"满200减30"},
    {"title":"活动名称","desc":"满200减50"}
    ],
    "cartList":[
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	}
    	]
	}
],
"noActionList":[
    {"actId":123,
    "title":"美容辅组工具品牌促销专场",
    "cartList":[
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	}
    	]
	},
	{"actId":123,
    "title":"美容辅组工具品牌促销专场",
    "cartList":[
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	},
    	{"oriRPrice":122,
    	 "rprice":122,
    	 "hdSPrice":0,
    	 "couponSPrice":0,
    	 "totalCount":1,
    	 "productId":122,
    	 "skuId":122,
    	 "skuSPVO":{
    		"productName":"2014秋装新款女装可脱卸领甜美韩版显瘦百搭短外套",
    		"picUrl":"/res/images/temp/demo.png",
    		"colorName":"黑色",
    		"linkUrl":"xxxx",
    		"skuSpecValueMap":{"size":"M"}
    	 }
    	}
    	]
	}
]
}



/>